insert into stocks (description, ticker, brokerTypeId) values
('Barclays 0-5 Year TIPS Bond ','STIP', 4),
('Barclays 1-3 Year Treasury Bond ','SHY', 4),
('Barclays 20+ Year Treasury Bond ','TLT', 4),
('Barclays 7-10 Year Treasury Bond ','IEF', 4),
('Barclays Agency Bond ','AGZ', 4),
('Barclays GNMA Bond ','GNMA', 4),
('Barclays Intermediate Government Credit Bond ','GVI', 4),
('Barclays MBS Bond ','MBB', 4),
('Barclays TIPS Bond ','TIP', 4),
('Barclays U.S. Treasury Bond ','GOVT', 4),
('Core Long-Term U.S. Bond ','ILTB', 4),
('Core MSCI EAFE ','IEFA', 4),
('Core MSCI Emerging Markets ','IEMG', 4),
('Core MSCI Total International Stock ','IXUS', 4),
('Core S&P 500 ','IVV', 4),
('Core S&P Mid-Cap ','IJH', 4),
('Core S&P Small-Cap ','IJR', 4),
('Core S&P Total U.S. Stock Market ','ITOT', 4),
('Core Short-Term U.S. Bond ','ISTB', 4),
('Core Total U.S. Bond Market ','AGG', 4),
('Dow Jones International Select Dividend Index ','IDV', 4),
('Dow Jones Select Dividend Index ','DVY', 4),
('Dow Jones U.S. Real Estate Index ','IYR', 4),
('Emerging Markets Dividend ','DVYE', 4),
('Emerging Markets Local Currency Bond ','LEMB', 4),
('Floating Rate Note ','FLOT', 4),
('FTSE EPRA/NAREIT Global Real Estate ex U.S. ','IFGL', 4),
('iBoxx $ High Yield Corporate Bond ','HYG', 4),
('iBoxx $ Investment Grade Corporate Bond ','LQD', 4),
('International Inflation-Linked Bond ','ITIP', 4),
('JPMorgan USD Emerging Markets Bond ','EMB', 4),
('MSCI ACWI Index ','ACWI', 4),
('MSCI All Country Asia ex Japan Index ','AAXJ', 4),
('MSCI BRIC Index ','BKF', 4),
('MSCI China Index ','MCHI', 4),
('MSCI EAFE Minimum Volatility ','EFAV', 4),
('MSCI EAFE Small-Cap Index ','SCZ', 4),
('MSCI Emerging Markets EMEA ','EEME', 4),
('MSCI Emerging Market Minimum Volatility Index ','EEMV', 4),
('MSCI Emerging Markets Small-Cap ','EEMS', 4),
('MSCI Frontier 100 Index ','FM', 4),
('MSCI Global Agriculture Producers ','VEGI', 4),
('MSCI Global Gold Miners ','RING', 4),
('MSCI Global Metals & Mining Producers ','PICK', 4),
('MSCI Global Silver Miners ','SLVP', 4),
('MSCI Japan Index ','EWJ', 4),
('MSCI USA Minimum Volatility Index ','USMV', 4),
('Russell Micro-Cap Index ','IWC', 4),
('S&P 100 Index ','OEF', 4),
('S&P 500 Growth Index ','IVW', 4),
('S&P 500 Value Index ','IVE', 4),
('S&P CA AMT-Free Municipal Bond ','CMF', 4),
('S&P Europe 350 Index ','IEV', 4),
('S&P India Nifty 50 Index ','INDY', 4),
('S&P Latin America 40 Index ','ILF', 4),
('S&P Mid-Cap 400 Growth Index ','IJK', 4),
('S&P Mid-Cap 400 Value Index ','IJJ', 4),
('S&P National AMT-Free Municipal Bond ','MUB', 4),
('S&P NY AMT-Free Municipal Bond ','NYF', 4),
('S&P S/T National AMT-Free Municipal Bond ','SUB', 4),
('S&P Small-Cap 600 Growth ','IJT', 4),
('S&P Small-Cap 600 Value Index ','IJS', 4),
('S&P U.S. Preferred Stock Index ','PFF', 4),
('S&P/Citi 1-3 Year International Treasury Bond ','ISHG', 4),
('S&P/Citi International Treasury Bond ','IGOV', 4);
